name: 'Gen openapi doc'
description: 'Gen openapi doc'
inputs:
  token:
    description: Github token.
    required: true
  repo:
    description: Repository name.
    required: true
  core-nest-module-version:
    description: Repository name.
    default: '1.0.0'
    required: false
runs:
  using: 'node16'
  main: 'lib/index.js'